# Generated by Django 4.1.3 on 2023-02-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_influencer_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopsCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Stors_Cat/')),
            ],
        ),
        migrations.AddField(
            model_name='shops',
            name='backgroundImage',
            field=models.ImageField(blank=True, null=True, upload_to='stor_background/'),
        ),
        migrations.AddField(
            model_name='shops',
            name='mainColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='subColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='cats',
            field=models.ManyToManyField(to='app.shopscat'),
        ),
    ]
