# Generated by Django 4.1.3 on 2023-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_images_remove_item_item_image_item_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ManyToManyField(blank=True, null=True, to='app.images'),
        ),
    ]
