# Generated by Django 4.1.3 on 2023-02-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='shiping',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shops',
            name='shiping2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
