# Generated by Django 4.1.3 on 2023-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_smedia_shops_sm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='locathion',
            new_name='city',
        ),
        migrations.AddField(
            model_name='checkout',
            name='current_city',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
