# Generated by Django 4.1.3 on 2023-02-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_rename_locathion_checkout_city_checkout_current_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopscover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ManyToManyField(blank=True, to='app.images')),
                ('items', models.ManyToManyField(blank=True, to='app.item')),
            ],
        ),
    ]
