# Generated by Django 4.1.3 on 2023-02-21 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_shopscover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='backgroundImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shopscover'),
        ),
    ]
