# Generated by Django 4.1.3 on 2023-02-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_shops_backgroundimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='cats',
            field=models.ManyToManyField(blank=True, to='app.shopscat'),
        ),
    ]
