# Generated by Django 4.1.3 on 2023-02-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_shops_cats'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='xitem',
        ),
        migrations.AddField(
            model_name='checkout',
            name='xitem',
            field=models.ManyToManyField(blank=True, to='app.item'),
        ),
    ]
