# Generated by Django 4.1.3 on 2023-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_cart_session_id_cart_uid_alter_cart_adder'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='iconeimage/'),
        ),
    ]
