# Generated by Django 4.1.3 on 2023-03-11 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_shops_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='iconeimage/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
