# Generated by Django 4.1.7 on 2023-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_shops_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='Active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
