# Generated by Django 4.1.3 on 2023-02-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otherInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('fullName', models.CharField(blank=True, max_length=120, null=True)),
                ('following', models.PositiveBigIntegerField(default=0)),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('postsCount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='OtherData/')),
                ('AcceptByAdmin', models.BooleanField(default=False)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='otherPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medai', models.FileField(blank=True, null=True, upload_to='')),
                ('caption', models.TextField(blank=True, null=True)),
                ('commintes', models.PositiveBigIntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('infl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.otherinfluencer')),
            ],
        ),
        migrations.CreateModel(
            name='otherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('total_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_communt', models.IntegerField(blank=True, default=0, null=True)),
                ('alike', models.FloatField(blank=True, default=0, null=True)),
                ('acommunt', models.FloatField(blank=True, default=0, null=True)),
                ('following', models.IntegerField(blank=True, default=0, null=True)),
                ('followers', models.IntegerField(blank=True, default=0, null=True)),
                ('communt_ratio', models.FloatField(blank=True, default=0, null=True)),
                ('post_count', models.IntegerField(blank=True, default=0, null=True)),
                ('er', models.FloatField(blank=True, default=0, null=True)),
                ('infl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.otherinfluencer')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.otherposts')),
            ],
        ),
    ]
