# Generated by Django 4.1.3 on 2023-03-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherposts',
            name='isvideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='otherposts',
            name='shortcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
